/* eslint-disable @typescript-eslint/no-non-null-assertion */
/**
 * Registre centralisé des modules SYGFP
 * Source unique de vérité pour la navigation et les routes
 *
 * RÈGLES:
 * - Tout nouveau module DOIT être ajouté ici avant de créer sa route
 * - Les routes dans App.tsx doivent correspondre à ce registre
 * - La sidebar génère son menu depuis ce registre
 *
 * CHAMPS:
 * - id: Identifiant unique du module
 * - name: Libellé affiché dans le menu
 * - icon: Icône Lucide
 * - route: Chemin de la route (null si groupe parent)
 * - parent: ID du module parent (null si racine)
 * - order: Ordre d'affichage dans le menu
 * - canonicalOrder: Ordre logique dans le workflow (peut différer de order)
 * - status: ready | beta | todo | deprecated
 * - isEnabled: Module activé ou non
 * - roles: Rôles autorisés ('all' pour tous)
 * - requiredCapabilities: Capacités requises (permissions spécifiques)
 * - stepCode: Code étape workflow (pour la chaîne de dépense)
 * - step: Numéro d'étape (affichage)
 * - badge/badgeKey: Configuration des badges de notification
 * - subSection: Sous-section pour le regroupement
 * - description: Description du module
 */

import {
  Home,
  Search,
  FileText,
  FileEdit,
  Tag,
  Briefcase,
  ShoppingCart,
  CreditCard,
  Receipt,
  FileCheck,
  Banknote,
  Wallet,
  ClipboardList,
  ArrowRightLeft,
  ArrowLeftRight,
  FileUp,
  History,
  Database,
  Building2,
  FileSignature,
  Truck,
  Landmark,
  DollarSign,
  Archive,
  BarChart3,
  Target,
  Calendar,
  Hash,
  Layers,
  BookOpen,
  Users,
  Shield,
  Lock,
  UserCog,
  Settings,
  Cog,
  Copy,
  TrendingUp,
  Activity,
  Bell,
  AlertTriangle,
  CheckSquare,
  User,
  TestTube,
  HelpCircle,
  Link,
  GitBranch,
  FileQuestion,
  Coins,
  ScanLine,
  ListChecks,
  type LucideIcon,
} from 'lucide-react';

// ============================================
// TYPES
// ============================================

export type ModuleStatus = 'ready' | 'beta' | 'todo' | 'deprecated';

export interface ModuleConfig {
  id: string;
  name: string;
  icon: LucideIcon;
  route: string | null;
  parent: string | null;
  order: number;
  canonicalOrder: number; // Ordre logique workflow (peut différer de order)
  status: ModuleStatus;
  isEnabled: boolean;
  roles: string[];
  requiredCapabilities?: string[];
  badge?: boolean;
  badgeKey?: string;
  description?: string;
  step?: number;
  stepCode?: string; // Code étape pour le workflow
  subSection?: string;
}

// ============================================
// CONSTANTES STEP CODES (chaîne de dépense)
// ============================================

export const STEP_CODES = {
  NOTE_SEF: 'NOTE_SEF',
  NOTE_AEF: 'NOTE_AEF',
  IMPUTATION: 'IMPUTATION',
  EXPRESSION_BESOIN: 'EXPRESSION_BESOIN',
  PASSATION_MARCHE: 'PASSATION_MARCHE',
  ENGAGEMENT: 'ENGAGEMENT',
  LIQUIDATION: 'LIQUIDATION',
  ORDONNANCEMENT: 'ORDONNANCEMENT',
  REGLEMENT: 'REGLEMENT',
} as const;

// ============================================
// REGISTRE PRINCIPAL DES MODULES
// ============================================

export const MODULES_REGISTRY: ModuleConfig[] = [
  // ========== ACCUEIL ==========
  {
    id: 'dashboard',
    name: 'Tableau de bord',
    icon: Home,
    route: '/',
    parent: null,
    order: 0,
    canonicalOrder: 0,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
    description: "Vue d'ensemble et indicateurs clés",
  },
  {
    id: 'recherche',
    name: 'Recherche Dossier',
    icon: Search,
    route: '/recherche',
    parent: null,
    order: 1,
    canonicalOrder: 1,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
    description: 'Recherche transversale de dossiers',
  },

  // ========== CHAÎNE DE LA DÉPENSE (groupe parent) ==========
  {
    id: 'chaine-depense',
    name: 'Chaîne de la Dépense',
    icon: CreditCard,
    route: null,
    parent: null,
    order: 2,
    canonicalOrder: 2,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
    description: '9 étapes du flux de dépense',
  },

  // ========== GESTION TÂCHES (groupe parent) ==========
  {
    id: 'gestion-taches',
    name: 'Gestion Tâches',
    icon: ListChecks,
    route: null,
    parent: null,
    order: 2.5,
    canonicalOrder: 2.5,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'dg', 'daaf', 'directeur', 'operateur'],
    description: 'Planification et exécution des tâches',
  },
  // Sous-groupe: Plannif. Tâches
  {
    id: 'plannif-taches',
    name: 'Plannif. Tâches',
    icon: Calendar,
    route: null,
    parent: 'gestion-taches',
    order: 1,
    canonicalOrder: 1,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf', 'directeur'],
    description: 'Planification des tâches et feuilles de route',
  },
  // Sous-groupe: Execution - Tâches
  {
    id: 'execution-taches',
    name: 'Execution - Tâches',
    icon: Activity,
    route: null,
    parent: 'gestion-taches',
    order: 2,
    canonicalOrder: 2,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'dg', 'daaf', 'directeur', 'operateur'],
    description: "Suivi de l'exécution des tâches",
  },

  {
    id: 'notes-sef',
    name: 'Notes SEF',
    icon: FileText,
    route: '/notes-sef',
    parent: 'chaine-depense',
    order: 1,
    canonicalOrder: 1,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
    badge: true,
    step: 1,
    stepCode: STEP_CODES.NOTE_SEF,
    description: 'Sans Engagement Financier',
  },
  {
    id: 'notes-aef',
    name: 'Notes AEF',
    icon: FileEdit,
    route: '/notes-aef',
    parent: 'chaine-depense',
    order: 2,
    canonicalOrder: 2,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
    badge: true,
    step: 2,
    stepCode: STEP_CODES.NOTE_AEF,
    description: 'Avec Engagement Financier',
  },
  {
    id: 'notes-dg-officielles',
    name: 'Notes DG',
    icon: FileSignature,
    route: '/notes-dg',
    parent: 'chaine-depense',
    order: 2.5,
    canonicalOrder: 2.5,
    status: 'ready',
    isEnabled: true,
    roles: ['dg', 'admin', 'daaf', 'directeur'],
    badge: false,
    description: 'Notes officielles du Directeur Général avec imputations',
  },
  {
    id: 'imputation',
    name: 'Imputation',
    icon: Tag,
    route: '/execution/imputation',
    parent: 'chaine-depense',
    order: 3,
    canonicalOrder: 3,
    status: 'ready',
    isEnabled: true,
    roles: ['sdct', 'daaf', 'cb'],
    requiredCapabilities: ['imputation.create', 'imputation.validate'],
    step: 3,
    stepCode: STEP_CODES.IMPUTATION,
    description: 'Imputation budgétaire',
  },
  {
    id: 'expression-besoin',
    name: 'Expression Besoin',
    icon: Briefcase,
    route: '/execution/expression-besoin',
    parent: 'chaine-depense',
    order: 4,
    canonicalOrder: 4,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
    step: 4,
    stepCode: STEP_CODES.EXPRESSION_BESOIN,
    description: 'Formalisation du besoin',
  },
  {
    id: 'passation-marche',
    name: 'Passation Marché',
    icon: ShoppingCart,
    route: '/marches',
    parent: 'chaine-depense',
    order: 5,
    canonicalOrder: 5,
    status: 'ready',
    isEnabled: true,
    roles: ['sdpm', 'daaf'],
    requiredCapabilities: ['marche.create', 'marche.validate'],
    step: 5,
    stepCode: STEP_CODES.PASSATION_MARCHE,
    description: 'Si montant > seuil',
  },
  {
    id: 'engagement',
    name: 'Engagement',
    icon: CreditCard,
    route: '/engagements',
    parent: 'chaine-depense',
    order: 6,
    canonicalOrder: 6,
    status: 'ready',
    isEnabled: true,
    roles: ['cb'],
    requiredCapabilities: ['engagement.create', 'engagement.validate'],
    badge: true,
    badgeKey: 'engagementsAValider',
    step: 6,
    stepCode: STEP_CODES.ENGAGEMENT,
    description: 'Réservation crédits',
  },
  {
    id: 'scanning-engagement',
    name: 'Scanning Engagement',
    icon: ScanLine,
    route: '/execution/scanning-engagement',
    parent: 'chaine-depense',
    order: 6.5,
    canonicalOrder: 6.5,
    status: 'ready',
    isEnabled: true,
    roles: ['cb', 'daaf', 'operateur'],
    requiredCapabilities: ['engagement.create'],
    badge: false,
    step: 6,
    stepCode: STEP_CODES.ENGAGEMENT,
    description: 'Numérisation pièces engagement',
  },
  {
    id: 'liquidation',
    name: 'Liquidation',
    icon: Receipt,
    route: '/liquidations',
    parent: 'chaine-depense',
    order: 7,
    canonicalOrder: 7,
    status: 'ready',
    isEnabled: true,
    roles: ['sdct', 'daaf'],
    requiredCapabilities: ['liquidation.create', 'liquidation.validate'],
    badge: true,
    badgeKey: 'liquidationsAValider',
    step: 7,
    stepCode: STEP_CODES.LIQUIDATION,
    description: 'Constatation service fait',
  },
  {
    id: 'scanning-liquidation',
    name: 'Scanning Liquidation',
    icon: ScanLine,
    route: '/execution/scanning-liquidation',
    parent: 'chaine-depense',
    order: 7.5,
    canonicalOrder: 7.5,
    status: 'ready',
    isEnabled: true,
    roles: ['daaf', 'cb', 'operateur'],
    requiredCapabilities: ['liquidation.create'],
    badge: false,
    step: 7,
    stepCode: STEP_CODES.LIQUIDATION,
    description: 'Numérisation pièces liquidation',
  },
  {
    id: 'ordonnancement',
    name: 'Ordonnancement',
    icon: FileCheck,
    route: '/ordonnancements',
    parent: 'chaine-depense',
    order: 8,
    canonicalOrder: 8,
    status: 'ready',
    isEnabled: true,
    roles: ['dg'],
    requiredCapabilities: ['ordonnancement.create', 'ordonnancement.sign'],
    badge: true,
    badgeKey: 'ordonnancementsAValider',
    step: 8,
    stepCode: STEP_CODES.ORDONNANCEMENT,
    description: 'Ordre de paiement',
  },
  {
    id: 'reglement',
    name: 'Règlement',
    icon: Banknote,
    route: '/reglements',
    parent: 'chaine-depense',
    order: 9,
    canonicalOrder: 9,
    status: 'ready',
    isEnabled: true,
    roles: ['tresorerie'],
    requiredCapabilities: ['reglement.execute'],
    step: 9,
    stepCode: STEP_CODES.REGLEMENT,
    description: 'Paiement effectif',
  },

  // ========== BUDGET (groupe parent) ==========
  {
    id: 'budget',
    name: 'Budget',
    icon: Wallet,
    route: null,
    parent: null,
    order: 3,
    canonicalOrder: 10,
    status: 'ready',
    isEnabled: true,
    roles: ['daaf', 'cb', 'admin'],
    description: 'Planification et structure budgétaire',
  },
  {
    id: 'structure-budgetaire',
    name: 'Structure Budgétaire',
    icon: Wallet,
    route: '/planification/structure',
    parent: 'budget',
    order: 1,
    canonicalOrder: 1,
    status: 'ready',
    isEnabled: true,
    roles: ['daaf', 'cb', 'admin'],
  },
  {
    id: 'planification-budget',
    name: 'Planification Budgétaire',
    icon: Target,
    route: '/planification/budget',
    parent: 'budget',
    order: 2,
    canonicalOrder: 2,
    status: 'ready',
    isEnabled: true,
    roles: ['daaf', 'cb', 'admin'],
  },
  {
    id: 'planification-physique',
    name: 'Planification Physique',
    icon: Activity,
    route: '/planification/physique',
    parent: 'budget',
    order: 3,
    canonicalOrder: 3,
    status: 'ready',
    isEnabled: true,
    roles: ['daaf', 'cb', 'admin'],
  },
  {
    id: 'plan-travail',
    name: 'Plan de Travail',
    icon: ClipboardList,
    route: '/planification/plan-travail',
    parent: 'budget',
    order: 4,
    canonicalOrder: 4,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
  },
  {
    id: 'virements',
    name: 'Virements & Ajustements',
    icon: ArrowRightLeft,
    route: '/planification/virements',
    parent: 'budget',
    order: 5,
    canonicalOrder: 5,
    status: 'ready',
    isEnabled: true,
    roles: ['cb', 'daaf'],
  },
  {
    id: 'notifications-budgetaires',
    name: 'Notifications Budgétaires',
    icon: Bell,
    route: '/planification/notifications',
    parent: 'budget',
    order: 6,
    canonicalOrder: 6,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf', 'cb', 'dg'],
    description: 'Gestion des notifications budgétaires',
  },
  {
    id: 'import-export-budget',
    name: 'Import / Export',
    icon: FileUp,
    route: '/planification/import-export',
    parent: 'budget',
    order: 7,
    canonicalOrder: 7,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf'],
  },
  // ---- Plannif. Tâches children ----
  {
    id: 'feuilles-route',
    name: 'Charg. feuilles de routes',
    icon: FileUp,
    route: '/planification/feuilles-route',
    parent: 'plannif-taches',
    order: 1,
    canonicalOrder: 1,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf', 'directeur'],
    description: 'Chargement et import des feuilles de route par direction',
  },
  {
    id: 'maj-feuilles-route',
    name: 'Mise à jour Feuilles',
    icon: FileEdit,
    route: '/planification/maj-feuilles-route',
    parent: 'plannif-taches',
    order: 2,
    canonicalOrder: 2,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf', 'directeur'],
    description: 'Réaménagement et modification des feuilles de routes',
  },
  // ---- Execution - Tâches children ----
  {
    id: 'soumissions-feuilles-route',
    name: 'Soumission feuilles',
    icon: FileCheck,
    route: '/planification/soumissions-feuilles-route',
    parent: 'execution-taches',
    order: 1,
    canonicalOrder: 1,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'dg', 'daaf', 'directeur'],
    description: 'Soumission des feuilles de route pour validation',
  },
  {
    id: 'taches-realisees',
    name: 'Tâches réalisées',
    icon: CheckSquare,
    route: '/gestion-taches/taches-realisees',
    parent: 'execution-taches',
    order: 2,
    canonicalOrder: 2,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'dg', 'daaf', 'directeur', 'operateur'],
    description: 'Liste des tâches réalisées',
  },
  {
    id: 'taches-differees',
    name: 'Tâches différées',
    icon: AlertTriangle,
    route: '/gestion-taches/taches-differees',
    parent: 'execution-taches',
    order: 3,
    canonicalOrder: 3,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'dg', 'daaf', 'directeur'],
    description: 'Liste des tâches différées ou bloquées',
  },
  {
    id: 'execution-physique',
    name: 'Suivi exécution',
    icon: ListChecks,
    route: '/planification/execution-physique',
    parent: 'execution-taches',
    order: 4,
    canonicalOrder: 4,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf', 'directeur', 'operateur'],
    description: "Suivi de l'avancement des activités",
  },
  // ---- État d'exécution (sous-groupe) ----
  {
    id: 'etat-execution-taches',
    name: "Etat d'exéc. Tâches",
    icon: BarChart3,
    route: null,
    parent: 'gestion-taches',
    order: 3,
    canonicalOrder: 3,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'dg', 'daaf', 'directeur'],
    description: "Suivi de l'exécution physique par Direction, Mission, OS",
  },
  // État d'exécution sub-items
  {
    id: 'exec-physique-mission',
    name: 'Exécution par mission',
    icon: Target,
    route: '/gestion-taches/etat-execution',
    parent: 'etat-execution-taches',
    order: 1,
    canonicalOrder: 1,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'dg', 'daaf', 'directeur'],
    description: 'Exécution physique par mission',
  },
  {
    id: 'exec-physique-os',
    name: 'Exécution par OS',
    icon: Target,
    route: '/gestion-taches/etat-execution?view=os',
    parent: 'etat-execution-taches',
    order: 2,
    canonicalOrder: 2,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'dg', 'daaf', 'directeur'],
    description: 'Exécution physique par objectif stratégique',
  },
  {
    id: 'exec-physique-projet',
    name: 'Exécution par projet',
    icon: Briefcase,
    route: '/gestion-taches/etat-execution?view=projet',
    parent: 'etat-execution-taches',
    order: 3,
    canonicalOrder: 3,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'dg', 'daaf', 'directeur'],
    description: 'Exécution physique par projet',
  },
  {
    id: 'exec-physique-activite',
    name: 'Exécution par activité',
    icon: Activity,
    route: '/gestion-taches/etat-execution?view=activite',
    parent: 'etat-execution-taches',
    order: 4,
    canonicalOrder: 4,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'dg', 'daaf', 'directeur'],
    description: 'Exécution physique par activité',
  },
  {
    id: 'historique-imports',
    name: 'Historique Imports',
    icon: History,
    route: '/planification/historique-imports',
    parent: 'budget',
    order: 8,
    canonicalOrder: 8,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf'],
  },
  {
    id: 'documentation-import',
    name: 'Documentation Import',
    icon: BookOpen,
    route: '/planification/documentation-import',
    parent: 'budget',
    order: 9,
    canonicalOrder: 9,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf'],
  },
  {
    id: 'aide-import',
    name: 'Aide Import Budget',
    icon: HelpCircle,
    route: '/planification/aide-import',
    parent: 'budget',
    order: 10,
    canonicalOrder: 10,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf'],
  },
  {
    id: 'import-budget-admin',
    name: 'Import Budget (Admin)',
    icon: Database,
    route: '/admin/import-budget',
    parent: 'budget',
    order: 11,
    canonicalOrder: 11,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
  },

  // ========== PROGRAMMATIQUE (groupe parent) ==========
  {
    id: 'programmatique',
    name: 'Programmatique',
    icon: BarChart3,
    route: null,
    parent: null,
    order: 3.5,
    canonicalOrder: 15,
    status: 'ready',
    isEnabled: true,
    roles: ['daaf', 'cb', 'admin', 'dg'],
    description: 'Gestion programmatique du budget',
  },
  {
    id: 'prog-charger-budget',
    name: 'Charger le Budget',
    icon: FileUp,
    route: '/programmatique/charger-budget',
    parent: 'programmatique',
    order: 1,
    canonicalOrder: 1,
    status: 'ready',
    isEnabled: true,
    roles: ['daaf', 'admin'],
    description: 'Import Excel du budget',
  },
  {
    id: 'prog-mise-a-jour',
    name: 'Mise à jour Budget',
    icon: FileEdit,
    route: '/programmatique/mise-a-jour',
    parent: 'programmatique',
    order: 2,
    canonicalOrder: 2,
    status: 'ready',
    isEnabled: true,
    roles: ['daaf', 'cb', 'admin'],
    description: 'Ajustements budgétaires avec justification',
  },
  {
    id: 'prog-liste-budget',
    name: 'Liste Budget',
    icon: ClipboardList,
    route: '/programmatique/liste-budget',
    parent: 'programmatique',
    order: 3,
    canonicalOrder: 3,
    status: 'ready',
    isEnabled: true,
    roles: ['daaf', 'cb', 'admin', 'dg', 'directeur'],
    description: 'Consultation avec drill-down',
  },
  {
    id: 'prog-reamenagement',
    name: 'Réaménagement',
    icon: ArrowLeftRight,
    route: '/programmatique/reamenagement',
    parent: 'programmatique',
    order: 4,
    canonicalOrder: 4,
    status: 'ready',
    isEnabled: true,
    roles: ['daaf', 'cb', 'admin'],
    description: 'Virements internes entre lignes',
  },

  // ========== CONTRACTUALISATION (groupe parent) ==========
  {
    id: 'contractualisation',
    name: 'Contractualisation',
    icon: FileSignature,
    route: null,
    parent: null,
    order: 4,
    canonicalOrder: 20,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
    description: 'Gestion des marchés et contrats',
  },
  {
    id: 'marches-contractualisation',
    name: 'Marchés',
    icon: ShoppingCart,
    route: '/marches',
    parent: 'contractualisation',
    order: 1,
    canonicalOrder: 1,
    status: 'ready',
    isEnabled: true,
    roles: ['sdpm', 'daaf', 'admin'],
    description: 'Gestion des marchés publics',
  },
  {
    id: 'lots-marches',
    name: 'Lots',
    icon: Layers,
    route: '/contractualisation/lots',
    parent: 'contractualisation',
    order: 2,
    canonicalOrder: 2,
    status: 'ready',
    isEnabled: true,
    roles: ['sdpm', 'daaf', 'admin'],
    description: 'Gestion des lots de marchés',
  },
  {
    id: 'soumissions-marches',
    name: 'Soumissions',
    icon: FileUp,
    route: '/contractualisation/soumissions',
    parent: 'contractualisation',
    order: 3,
    canonicalOrder: 3,
    status: 'ready',
    isEnabled: true,
    roles: ['sdpm', 'daaf', 'admin'],
    description: 'Gestion des soumissions aux marchés',
  },
  {
    id: 'contrats',
    name: 'Contrats',
    icon: FileSignature,
    route: '/contractualisation/contrats',
    parent: 'contractualisation',
    order: 4,
    canonicalOrder: 4,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
    description: 'Gestion des contrats',
  },

  // ========== PRESTATAIRES (groupe parent) ==========
  {
    id: 'prestataires-group',
    name: 'Prestataires',
    icon: Building2,
    route: null,
    parent: null,
    order: 4.5,
    canonicalOrder: 21,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
    description: 'Gestion des prestataires',
  },
  {
    id: 'prestataires-ajouter',
    name: 'Ajouter un prestataire',
    icon: User,
    route: '/contractualisation/prestataires?action=new',
    parent: 'prestataires-group',
    order: 1,
    canonicalOrder: 1,
    status: 'ready',
    isEnabled: true,
    roles: ['daaf', 'sdpm', 'admin'],
    description: "Ajout d'un nouveau prestataire",
  },
  {
    id: 'prestataires-liste',
    name: 'Liste',
    icon: ClipboardList,
    route: '/contractualisation/prestataires',
    parent: 'prestataires-group',
    order: 2,
    canonicalOrder: 2,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
    description: 'Liste des prestataires',
  },

  // ========== GESTION COMPLÉMENTAIRE (groupe parent) ==========
  {
    id: 'gestion',
    name: 'Gestion',
    icon: Briefcase,
    route: null,
    parent: null,
    order: 5,
    canonicalOrder: 30,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
    description: 'Modules complémentaires',
  },
  {
    id: 'approvisionnement',
    name: 'Approvisionnement',
    icon: Truck,
    route: '/approvisionnement',
    parent: 'gestion',
    order: 1,
    canonicalOrder: 1,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
  },
  {
    id: 'tresorerie',
    name: 'Trésorerie',
    icon: Landmark,
    route: null,
    parent: 'gestion',
    order: 2,
    canonicalOrder: 2,
    status: 'ready',
    isEnabled: true,
    roles: ['tresorerie', 'dg', 'daaf', 'admin'],
  },
  {
    id: 'tresorerie-tableau-bord',
    name: 'Tableau de bord',
    icon: TrendingUp,
    route: '/tresorerie',
    parent: 'tresorerie',
    order: 1,
    canonicalOrder: 1,
    status: 'ready',
    isEnabled: true,
    roles: ['tresorerie', 'dg', 'daaf', 'admin'],
  },
  {
    id: 'tresorerie-appro-banque',
    name: 'Appro. Banque',
    icon: Building2,
    route: '/tresorerie/approvisionnements/banque',
    parent: 'tresorerie',
    order: 2,
    canonicalOrder: 2,
    status: 'ready',
    isEnabled: true,
    roles: ['tresorerie', 'dg', 'daaf', 'admin'],
  },
  {
    id: 'tresorerie-appro-caisse',
    name: 'Appro. Caisse',
    icon: Wallet,
    route: '/tresorerie/approvisionnements/caisse',
    parent: 'tresorerie',
    order: 3,
    canonicalOrder: 3,
    status: 'ready',
    isEnabled: true,
    roles: ['tresorerie', 'dg', 'daaf', 'admin'],
  },
  {
    id: 'tresorerie-mvt-banque',
    name: 'Mouvements Banque',
    icon: ArrowLeftRight,
    route: '/tresorerie/mouvements/banque',
    parent: 'tresorerie',
    order: 4,
    canonicalOrder: 4,
    status: 'ready',
    isEnabled: true,
    roles: ['tresorerie', 'dg', 'daaf', 'admin'],
  },
  {
    id: 'tresorerie-mvt-caisse',
    name: 'Mouvements Caisse',
    icon: ArrowLeftRight,
    route: '/tresorerie/mouvements/caisse',
    parent: 'tresorerie',
    order: 5,
    canonicalOrder: 5,
    status: 'ready',
    isEnabled: true,
    roles: ['tresorerie', 'dg', 'daaf', 'admin'],
  },
  {
    id: 'recettes',
    name: 'Recettes',
    icon: DollarSign,
    route: '/recettes',
    parent: 'gestion',
    order: 3,
    canonicalOrder: 3,
    status: 'ready',
    isEnabled: true,
    roles: ['daaf', 'tresorerie'],
  },
  {
    id: 'comptabilite-matiere',
    name: 'Comptabilité Matière',
    icon: Archive,
    route: '/contractualisation/comptabilite-matiere',
    parent: 'gestion',
    order: 4,
    canonicalOrder: 4,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
  },

  // ========== SUIVI DOSSIERS ==========
  {
    id: 'suivi-dossiers',
    name: 'Suivi Dossiers',
    icon: ClipboardList,
    route: '/suivi-dossiers',
    parent: null,
    order: 5.5,
    canonicalOrder: 35,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
    description: 'Vue unifiée des dossiers et leur progression dans la chaîne de dépense',
  },

  // ========== EXÉCUTION BUDGÉTAIRE (groupe parent) ==========
  {
    id: 'execution-budgetaire',
    name: 'Exécution Budgétaire',
    icon: Activity,
    route: null,
    parent: null,
    order: 6,
    canonicalOrder: 40,
    status: 'ready',
    isEnabled: true,
    roles: ['daaf', 'cb', 'dg'],
    description: "Suivi de l'exécution",
  },
  {
    id: 'dashboard-execution',
    name: 'Tableau de bord',
    icon: TrendingUp,
    route: '/execution/dashboard',
    parent: 'execution-budgetaire',
    order: 1,
    canonicalOrder: 1,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
  },
  {
    id: 'dashboard-dg',
    name: 'Dashboard DG',
    icon: BarChart3,
    route: '/execution/dashboard-dg',
    parent: 'execution-budgetaire',
    order: 1.5,
    canonicalOrder: 1.5,
    status: 'ready',
    isEnabled: true,
    roles: ['dg', 'admin'],
    description: 'Vue consolidée Direction Générale',
  },
  {
    id: 'dashboard-direction',
    name: 'Dashboard Direction',
    icon: Building2,
    route: '/execution/dashboard-direction',
    parent: 'execution-budgetaire',
    order: 1.6,
    canonicalOrder: 1.6,
    status: 'ready',
    isEnabled: true,
    roles: ['directeur', 'all'],
    description: 'Vue par Direction',
  },
  {
    id: 'passation-marche-execution',
    name: 'Passation Marché',
    icon: ShoppingCart,
    route: '/execution/passation-marche',
    parent: 'execution-budgetaire',
    order: 2,
    canonicalOrder: 2,
    status: 'ready',
    isEnabled: true,
    roles: ['sdpm', 'daaf'],
  },

  // ========== RAPPORTS (groupe parent) ==========
  {
    id: 'rapports',
    name: 'Rapports',
    icon: BarChart3,
    route: null,
    parent: null,
    order: 7,
    canonicalOrder: 50,
    status: 'ready',
    isEnabled: true,
    roles: ['daaf', 'cb', 'dg'],
    description: 'États et analyses',
  },
  {
    id: 'etats-execution',
    name: "États d'exécution",
    icon: BarChart3,
    route: '/etats-execution',
    parent: 'rapports',
    order: 1,
    canonicalOrder: 1,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
  },
  {
    id: 'alertes-budgetaires',
    name: 'Alertes Budgétaires',
    icon: Target,
    route: '/alertes-budgetaires',
    parent: 'rapports',
    order: 2,
    canonicalOrder: 2,
    status: 'ready',
    isEnabled: true,
    roles: ['cb', 'daaf'],
  },

  // ========== UTILISATEURS (groupe parent) ==========
  {
    id: 'utilisateurs-group',
    name: 'Utilisateurs',
    icon: Users,
    route: null,
    parent: null,
    order: 7.5,
    canonicalOrder: 55,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    description: 'Gestion des utilisateurs du système',
  },
  {
    id: 'utilisateurs-ajout',
    name: 'Ajout',
    icon: User,
    route: '/admin/utilisateurs?action=new',
    parent: 'utilisateurs-group',
    order: 1,
    canonicalOrder: 1,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    description: 'Ajouter un utilisateur',
  },
  {
    id: 'utilisateurs-actifs',
    name: 'Liste user actifs',
    icon: Users,
    route: '/admin/utilisateurs?status=actif',
    parent: 'utilisateurs-group',
    order: 2,
    canonicalOrder: 2,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    description: 'Liste des utilisateurs actifs',
  },
  {
    id: 'utilisateurs-desactives',
    name: 'Liste user désactivés',
    icon: Users,
    route: '/admin/utilisateurs?status=inactif',
    parent: 'utilisateurs-group',
    order: 3,
    canonicalOrder: 3,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    description: 'Liste des utilisateurs désactivés',
  },

  // ========== PARAMÉTRAGE (groupe parent) ==========
  {
    id: 'parametrage',
    name: 'Paramétrage',
    icon: Cog,
    route: null,
    parent: null,
    order: 8,
    canonicalOrder: 60,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'dg'],
    description: 'Configuration système',
  },

  // Sous-section: Référentiels
  {
    id: 'exercices',
    name: 'Exercices Budgétaires',
    icon: Calendar,
    route: '/admin/exercices',
    parent: 'parametrage',
    order: 1,
    canonicalOrder: 1,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    subSection: 'Référentiels',
  },
  {
    id: 'parametres-programmatiques',
    name: 'Paramètres Programmatiques',
    icon: Target,
    route: '/admin/parametres-programmatiques',
    parent: 'parametrage',
    order: 2,
    canonicalOrder: 2,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    subSection: 'Référentiels',
  },
  {
    id: 'architecture',
    name: 'Architecture SYGFP',
    icon: Database,
    route: '/admin/architecture',
    parent: 'parametrage',
    order: 3,
    canonicalOrder: 3,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    subSection: 'Référentiels',
  },
  {
    id: 'codification',
    name: 'Règles de Codification',
    icon: Hash,
    route: '/admin/codification',
    parent: 'parametrage',
    order: 4,
    canonicalOrder: 4,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    subSection: 'Référentiels',
  },
  {
    id: 'secteurs-activite',
    name: "Secteurs d'Activité",
    icon: Layers,
    route: '/admin/secteurs-activite',
    parent: 'parametrage',
    order: 5,
    canonicalOrder: 5,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    subSection: 'Référentiels',
  },
  {
    id: 'dictionnaire',
    name: 'Dictionnaire Variables',
    icon: BookOpen,
    route: '/admin/dictionnaire',
    parent: 'parametrage',
    order: 6,
    canonicalOrder: 6,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    subSection: 'Référentiels',
  },
  {
    id: 'documentation-modules',
    name: 'Documentation Modules',
    icon: FileQuestion,
    route: '/admin/documentation',
    parent: 'parametrage',
    order: 7,
    canonicalOrder: 7,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    subSection: 'Référentiels',
  },

  // Sous-section: Utilisateurs
  {
    id: 'utilisateurs',
    name: 'Gestion Utilisateurs',
    icon: Users,
    route: '/admin/utilisateurs',
    parent: 'parametrage',
    order: 10,
    canonicalOrder: 10,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    subSection: 'Utilisateurs',
  },
  {
    id: 'roles',
    name: 'Profils & Rôles',
    icon: Shield,
    route: '/admin/roles',
    parent: 'parametrage',
    order: 11,
    canonicalOrder: 11,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    subSection: 'Utilisateurs',
  },
  {
    id: 'autorisations',
    name: 'Autorisations',
    icon: Lock,
    route: '/admin/autorisations',
    parent: 'parametrage',
    order: 12,
    canonicalOrder: 12,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    subSection: 'Utilisateurs',
  },
  {
    id: 'delegations',
    name: 'Délégations',
    icon: UserCog,
    route: '/admin/delegations',
    parent: 'parametrage',
    order: 13,
    canonicalOrder: 13,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    subSection: 'Utilisateurs',
  },

  // Sous-section: Système
  {
    id: 'parametres-systeme',
    name: 'Paramètres Système',
    icon: Settings,
    route: '/admin/parametres',
    parent: 'parametrage',
    order: 20,
    canonicalOrder: 20,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    subSection: 'Système',
  },
  {
    id: 'parametres-exercice',
    name: 'Paramètres Exercice',
    icon: Calendar,
    route: '/admin/parametres-exercice',
    parent: 'parametrage',
    order: 21,
    canonicalOrder: 21,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    subSection: 'Système',
  },
  {
    id: 'journal-audit',
    name: "Journal d'Audit",
    icon: ClipboardList,
    route: '/admin/journal-audit',
    parent: 'parametrage',
    order: 22,
    canonicalOrder: 22,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'dg'],
    subSection: 'Système',
  },
  {
    id: 'matrice-raci',
    name: 'Matrice RACI',
    icon: GitBranch,
    route: '/admin/raci',
    parent: 'parametrage',
    order: 23,
    canonicalOrder: 23,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    subSection: 'Système',
  },
  {
    id: 'checklist-production',
    name: 'Checklist Production',
    icon: CheckSquare,
    route: '/admin/checklist-production',
    parent: 'parametrage',
    order: 24,
    canonicalOrder: 24,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    subSection: 'Système',
  },

  // Sous-section: Finance
  // ---- Comptes Bancaires (sous-groupe) ----
  {
    id: 'comptes-bancaires',
    name: 'Comptes Bancaires',
    icon: Landmark,
    route: null,
    parent: 'parametrage',
    order: 25,
    canonicalOrder: 25,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf', 'tresorerie', 'cb'],
    subSection: 'Finance',
  },
  {
    id: 'comptes-bancaires-actifs',
    name: 'CB actifs',
    icon: Landmark,
    route: '/admin/comptes-bancaires?status=actif',
    parent: 'comptes-bancaires',
    order: 1,
    canonicalOrder: 1,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf', 'tresorerie', 'cb'],
    description: 'Comptes bancaires actifs',
  },
  {
    id: 'comptes-bancaires-inactifs',
    name: 'CB Inactifs',
    icon: Landmark,
    route: '/admin/comptes-bancaires?status=inactif',
    parent: 'comptes-bancaires',
    order: 2,
    canonicalOrder: 2,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf', 'tresorerie', 'cb'],
    description: 'Comptes bancaires inactifs',
  },
  // ---- Origine des Fonds (sous-groupe) ----
  {
    id: 'origines-fonds',
    name: 'Origine des Fonds',
    icon: Coins,
    route: null,
    parent: 'parametrage',
    order: 26,
    canonicalOrder: 26,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf'],
    subSection: 'Finance',
  },
  {
    id: 'origines-fonds-actives',
    name: 'Origines Fonds actives',
    icon: Coins,
    route: '/admin/origines-fonds?status=actif',
    parent: 'origines-fonds',
    order: 1,
    canonicalOrder: 1,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf'],
    description: 'Origines de fonds actives',
  },
  {
    id: 'origines-fonds-inactives',
    name: 'Origines Fonds Inactifs',
    icon: Coins,
    route: '/admin/origines-fonds?status=inactif',
    parent: 'origines-fonds',
    order: 2,
    canonicalOrder: 2,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf'],
    description: 'Origines de fonds inactives',
  },
  // ---- Approvisionnement (sous-groupe) ----
  {
    id: 'param-approvisionnement',
    name: 'Approvisionnement',
    icon: Truck,
    route: null,
    parent: 'parametrage',
    order: 27,
    canonicalOrder: 27,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf', 'tresorerie'],
    subSection: 'Finance',
  },
  {
    id: 'param-appro-compte-bancaire',
    name: 'Compte Bancaire',
    icon: Building2,
    route: '/tresorerie/approvisionnements/banque',
    parent: 'param-approvisionnement',
    order: 1,
    canonicalOrder: 1,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf', 'tresorerie'],
    description: 'Approvisionnements compte bancaire',
  },
  {
    id: 'param-appro-caisse',
    name: 'Caisse',
    icon: Wallet,
    route: '/tresorerie/approvisionnements/caisse',
    parent: 'param-approvisionnement',
    order: 2,
    canonicalOrder: 2,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf', 'tresorerie'],
    description: 'Approvisionnements caisse',
  },
  // ---- Mouvements (sous-groupe) ----
  {
    id: 'param-mouvements',
    name: 'Mouvements',
    icon: ArrowLeftRight,
    route: null,
    parent: 'parametrage',
    order: 28,
    canonicalOrder: 28,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf', 'tresorerie'],
    subSection: 'Finance',
  },
  {
    id: 'param-mvt-compte-bancaire',
    name: 'Compte Bancaire',
    icon: Building2,
    route: '/tresorerie/mouvements/banque',
    parent: 'param-mouvements',
    order: 1,
    canonicalOrder: 1,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf', 'tresorerie'],
    description: 'Mouvements compte bancaire',
  },
  {
    id: 'param-mvt-caisse',
    name: 'Caisse',
    icon: Wallet,
    route: '/tresorerie/mouvements/caisse',
    parent: 'param-mouvements',
    order: 2,
    canonicalOrder: 2,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf', 'tresorerie'],
    description: 'Mouvements caisse',
  },
  // ---- Programmatique (sous-groupe dans Paramétrage) ----
  {
    id: 'param-programmatique',
    name: 'Programmatique',
    icon: BarChart3,
    route: null,
    parent: 'parametrage',
    order: 29,
    canonicalOrder: 29,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf', 'cb'],
    subSection: 'Finance',
  },
  {
    id: 'param-prog-charger',
    name: 'Charger le budget',
    icon: FileUp,
    route: '/programmatique/charger-budget',
    parent: 'param-programmatique',
    order: 1,
    canonicalOrder: 1,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf'],
    description: 'Charger un nouveau budget',
  },
  {
    id: 'param-prog-maj',
    name: 'Mise à jour du Budget',
    icon: FileEdit,
    route: '/programmatique/mise-a-jour',
    parent: 'param-programmatique',
    order: 2,
    canonicalOrder: 2,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf', 'cb'],
    description: 'Mise à jour du budget existant',
  },
  {
    id: 'param-prog-liste',
    name: 'Liste Budget',
    icon: ClipboardList,
    route: '/programmatique/liste-budget',
    parent: 'param-programmatique',
    order: 3,
    canonicalOrder: 3,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf', 'cb', 'dg'],
    description: 'Liste des budgets',
  },
  {
    id: 'param-prog-reamenagement',
    name: 'Liste reamanagement',
    icon: ArrowLeftRight,
    route: '/programmatique/reamenagement',
    parent: 'param-programmatique',
    order: 4,
    canonicalOrder: 4,
    status: 'ready',
    isEnabled: true,
    roles: ['admin', 'daaf', 'cb'],
    description: 'Réaménagements budgétaires',
  },

  // Sous-section: Outils
  {
    id: 'doublons',
    name: 'Gestion Doublons',
    icon: Copy,
    route: '/admin/doublons',
    parent: 'parametrage',
    order: 30,
    canonicalOrder: 30,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    subSection: 'Outils',
  },
  {
    id: 'compteurs-references',
    name: 'Compteurs Références',
    icon: Hash,
    route: '/admin/compteurs-references',
    parent: 'parametrage',
    order: 31,
    canonicalOrder: 31,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    subSection: 'Outils',
  },
  {
    id: 'liens-lambda',
    name: 'Liens Lambda',
    icon: Link,
    route: '/admin/liens-lambda',
    parent: 'parametrage',
    order: 32,
    canonicalOrder: 32,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    subSection: 'Outils',
  },
  {
    id: 'test-non-regression',
    name: 'Test Non-Régression',
    icon: TestTube,
    route: '/admin/test-non-regression',
    parent: 'parametrage',
    order: 33,
    canonicalOrder: 33,
    status: 'ready',
    isEnabled: true,
    roles: ['admin'],
    subSection: 'Outils',
  },

  // ========== MODULES UTILISATEUR (non affichés dans menu principal) ==========
  {
    id: 'notifications',
    name: 'Notifications',
    icon: Bell,
    route: '/notifications',
    parent: null,
    order: 100,
    canonicalOrder: 100,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
    description: 'Centre de notifications',
  },
  {
    id: 'alertes',
    name: 'Alertes',
    icon: AlertTriangle,
    route: '/alertes',
    parent: null,
    order: 101,
    canonicalOrder: 101,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
  },
  {
    id: 'taches',
    name: 'Mes Tâches',
    icon: CheckSquare,
    route: '/taches',
    parent: null,
    order: 102,
    canonicalOrder: 102,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
  },
  {
    id: 'profil',
    name: 'Mon Profil',
    icon: User,
    route: '/mon-profil',
    parent: null,
    order: 103,
    canonicalOrder: 103,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
  },

  // ========== ROUTES DÉTAIL (non affichées dans menu) ==========
  {
    id: 'note-sef-detail',
    name: 'Détail Note SEF',
    icon: FileText,
    route: '/notes-sef/:id',
    parent: null,
    order: 200,
    canonicalOrder: 200,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
  },
  {
    id: 'note-sef-validation',
    name: 'Validation Notes SEF',
    icon: FileCheck,
    route: '/notes-sef/validation',
    parent: null,
    order: 201,
    canonicalOrder: 201,
    status: 'ready',
    isEnabled: true,
    roles: ['dg', 'admin'],
  },
  {
    id: 'note-aef-detail',
    name: 'Détail Note AEF',
    icon: FileEdit,
    route: '/notes-aef/:id',
    parent: null,
    order: 202,
    canonicalOrder: 202,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
  },
  {
    id: 'note-aef-validation',
    name: 'Validation Notes AEF',
    icon: FileCheck,
    route: '/notes-aef/validation',
    parent: null,
    order: 203,
    canonicalOrder: 203,
    status: 'ready',
    isEnabled: true,
    roles: ['directeur', 'dg', 'admin'],
  },
  {
    id: 'note-dg-validation',
    name: 'Validation Notes DG',
    icon: FileCheck,
    route: '/notes-dg/validation',
    parent: null,
    order: 204,
    canonicalOrder: 204,
    status: 'ready',
    isEnabled: true,
    roles: ['dg', 'admin'],
    description: 'Validation des Notes Direction Générale',
  },
  {
    id: 'dg-notes-a-valider',
    name: 'Notes à valider (DG)',
    icon: FileCheck,
    route: '/dg/notes-a-valider',
    parent: 'chaine-depense',
    order: 1.5,
    canonicalOrder: 1.5,
    status: 'ready',
    isEnabled: true,
    roles: ['dg', 'admin'],
    badge: true,
    description: "File d'attente des notes SEF à valider par le DG",
  },

  {
    id: 'dossier-detail',
    name: 'Détail Dossier',
    icon: ClipboardList,
    route: '/suivi-dossiers/:id',
    parent: null,
    order: 210,
    canonicalOrder: 210,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
    description: "Vue détaillée d'un dossier avec timeline chaîne de dépense",
  },

  // ========== ROUTES AUTH (hors layout) ==========
  {
    id: 'auth-login',
    name: 'Connexion',
    icon: User,
    route: '/auth',
    parent: null,
    order: 300,
    canonicalOrder: 300,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
  },
  {
    id: 'select-exercice',
    name: 'Sélection Exercice',
    icon: Calendar,
    route: '/select-exercice',
    parent: null,
    order: 301,
    canonicalOrder: 301,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
  },
  {
    id: 'no-open-exercice',
    name: 'Aucun exercice ouvert',
    icon: AlertTriangle,
    route: '/no-open-exercice',
    parent: null,
    order: 302,
    canonicalOrder: 302,
    status: 'ready',
    isEnabled: true,
    roles: ['all'],
    description: "Page affichée quand aucun exercice budgétaire n'est ouvert",
  },
];

// ============================================
// HELPER FUNCTIONS
// ============================================

/**
 * Récupère un module par son ID
 */
export const getModuleById = (id: string): ModuleConfig | undefined =>
  MODULES_REGISTRY.find((m) => m.id === id);

/**
 * Récupère un module par sa route
 */
export const getModuleByRoute = (route: string): ModuleConfig | undefined =>
  MODULES_REGISTRY.find((m) => m.route === route);

/**
 * Récupère les enfants d'un module parent (modules activés uniquement)
 */
export const getChildModules = (parentId: string): ModuleConfig[] =>
  MODULES_REGISTRY.filter((m) => m.parent === parentId && m.isEnabled).sort(
    (a, b) => a.order - b.order
  );

/**
 * Récupère les modules racine (sans parent) pour le menu principal
 */
export const getRootModules = (): ModuleConfig[] =>
  MODULES_REGISTRY.filter((m) => m.parent === null && m.order < 100 && m.isEnabled).sort(
    (a, b) => a.order - b.order
  );

/**
 * Récupère tous les modules avec une route (pour vérification)
 */
export const getRoutedModules = (): ModuleConfig[] =>
  MODULES_REGISTRY.filter((m) => m.route !== null && m.isEnabled);

/**
 * Récupère les modules par rôle
 */
export const getModulesByRole = (role: string): ModuleConfig[] =>
  MODULES_REGISTRY.filter(
    (m) => m.isEnabled && (m.roles.includes('all') || m.roles.includes(role))
  );

/**
 * Récupère les modules par statut
 */
export const getModulesByStatus = (status: ModuleStatus): ModuleConfig[] =>
  MODULES_REGISTRY.filter((m) => m.status === status);

/**
 * Récupère les modules avec badge
 */
export const getModulesWithBadge = (): ModuleConfig[] =>
  MODULES_REGISTRY.filter((m) => m.badge === true && m.isEnabled);

/**
 * Récupère les sous-sections d'un groupe
 */
export const getSubSections = (parentId: string): string[] => {
  const children = getChildModules(parentId);
  const sections = new Set<string>();
  children.forEach((m) => {
    if (m.subSection) sections.add(m.subSection);
  });
  return Array.from(sections);
};

/**
 * Récupère les modules d'une sous-section
 */
export const getModulesBySubSection = (parentId: string, subSection: string): ModuleConfig[] =>
  MODULES_REGISTRY.filter(
    (m) => m.parent === parentId && m.subSection === subSection && m.isEnabled
  ).sort((a, b) => a.order - b.order);

/**
 * Vérifie si un module existe
 */
export const moduleExists = (id: string): boolean => MODULES_REGISTRY.some((m) => m.id === id);

/**
 * Vérifie si une route est enregistrée
 */
export const routeExists = (route: string): boolean =>
  MODULES_REGISTRY.some((m) => m.route === route);

/**
 * Récupère un module par son stepCode
 */
export const getModuleByStepCode = (stepCode: string): ModuleConfig | undefined =>
  MODULES_REGISTRY.find((m) => m.stepCode === stepCode);

/**
 * Récupère les modules de la chaîne de dépense dans l'ordre canonique
 */
export const getChaineDepenseModules = (): ModuleConfig[] =>
  MODULES_REGISTRY.filter((m) => m.parent === 'chaine-depense' && m.isEnabled).sort(
    (a, b) => a.canonicalOrder - b.canonicalOrder
  );

/**
 * Vérifie si un utilisateur peut accéder à un module
 */
export const canAccessModule = (
  moduleId: string,
  userRoles: string[],
  userCapabilities: string[] = []
): boolean => {
  const module = getModuleById(moduleId);
  if (!module || !module.isEnabled) return false;

  // Vérifier les rôles
  const hasRole = module.roles.includes('all') || module.roles.some((r) => userRoles.includes(r));

  // Vérifier les capacités si définies
  const hasCapabilities =
    !module.requiredCapabilities ||
    module.requiredCapabilities.every((c) => userCapabilities.includes(c));

  return hasRole && hasCapabilities;
};

/**
 * Récupère tous les modules "todo" (Coming Soon)
 */
export const getComingSoonModules = (): ModuleConfig[] =>
  MODULES_REGISTRY.filter((m) => m.status === 'todo');

/**
 * Génère une liste de vérification des routes pour le debug
 */
export const getRouteVerificationList = (): {
  route: string;
  moduleId: string;
  status: ModuleStatus;
}[] =>
  MODULES_REGISTRY.filter((m) => m.route !== null).map((m) => ({
    route: m.route!,
    moduleId: m.id,
    status: m.status,
  }));
