-- Insert NBE codes part 5/10 (53 codes from 601510 to 614600)
INSERT INTO public.nomenclature_nbe (code, libelle, est_active) VALUES
('601510', 'Achats de matières premières', true),
('601520', 'Achats de matières consommables', true),
('601530', 'Achats d''emballages commerciaux', true),
('601590', 'Autres achats de petits matériels et fournitures techniques', true),
('601600', 'Achats d''alimentation (non destinés au personnel)', true),
('601700', 'Achats d''habillement (hors personnel)', true),
('601800', 'Achats de produits pharmaceutiques, médicaux et vétérinaires', true),
('601910', 'Fournitures d''hygiène et de santé', true),
('601990', 'Autres achats de fournitures', true),
('603100', 'Variations  de stocks de marchandises', true),
('603200', 'Variations  de stocks de matières premières', true),
('603310', 'Matières consommables', true),
('603320', 'Carburant et lubrifiants', true),
('603330', 'Fournitures de bureau', true),
('603400', 'Variations  de stocks des produits et services en cours', true),
('603500', 'Variations  de stocks des produits finis', true),
('605100', 'Branchements et raccordement des compteurs', true),
('605200', 'Abonnements et consommation d''eau', true),
('605300', 'Abonnements et consommation d''électricité', true),
('605400', 'Abonnements et consommation de gaz', true),
('605900', 'Autres sources d''énergie', true),
('609100', 'Achats de marchandises', true),
('609200', 'Frets et transports sur achats', true),
('609900', 'Autres achats de biens', true),
('611100', 'Frais de transport des agents en mission à l''intérieur', true),
('611200', 'Indemnités de mission à l''intérieur', true),
('611300', 'Frais de transport des agents en mission à l''étranger', true),
('611400', 'Indemnités de mission à l''étranger', true),
('611500', 'Frais de transport des missionnaires non agents de l''Etat', true),
('611600', 'Indemnités de mission des missionnaires non agents de l''Etat', true),
('611700', 'Frais de transports des étudiants', true),
('611800', 'Frais de voyage des coopérants et autres expatriés', true),
('611900', 'Autres frais de transport et de mission', true),
('611910', 'Transports de personnes (sauf personnel)', true),
('611920', 'Transports et frets sur ventes', true),
('611990', 'Loyers et charges locatives', true),
('612100', 'Loyers et charges locatives des locaux (hors logements de personnel)', true),
('612200', 'Loyers avec option d''achat', true),
('612300', 'Location machines et matériel technique', true),
('612400', 'Locations de matériel informatique', true),
('612500', 'Location centraux téléphoniques, téléphones, télécopieurs et matériels de télécommunication', true),
('612700', 'Locations de véhicules', true),
('612900', 'Autres locations', true),
('614110', 'Entretien des locaux', true),
('614120', 'Produits d''entretien', true),
('614130', 'Matériaux de construction pour usage interne', true),
('614140', 'Entretien et réparations des bâtiments', true),
('614150', 'Entretien des espaces verts et autres sites aménagés', true),
('614200', 'Entretien des ascenseurs', true),
('614300', 'Entretien des installations électriques, climatiseurs, sanitaires et plomberies', true),
('614400', 'Entretien et maintenance des mobiliers et matériels informatiques', true),
('614500', 'Entretien et maintenance des centraux téléphoniques, téléphones, télécopieurs et matériel de télécommunication', true),
('614600', 'Entretien et maintenance des mobiliers et matériels (sauf informatiques)', true)
ON CONFLICT (code) DO UPDATE SET 
  libelle = EXCLUDED.libelle,
  est_active = true;