-- Insert NBE codes part 4/10 (53 codes from 271700 to 601400)
INSERT INTO public.nomenclature_nbe (code, libelle, est_active) VALUES
('271700', 'Avances à l''étranger', true),
('271900', 'Autres avances', true),
('273100', 'Prêts aux Sociétés d''Etat', true),
('273200', 'Prêts aux Sociétés d''Economie Mixte', true),
('274100', 'Prêts aux institutions financières à l''intérieur', true),
('274200', 'Prêts aux institutions financières à l''extérieur', true),
('275100', 'Prêts aux entreprises privées non financières', true),
('275200', 'Prêts au personnel pour achat de logement', true),
('275300', 'Prêts au personnel pour achat de véhicules', true),
('275400', 'Autres prêts au personnel', true),
('275900', 'Autres prêts intérieurs', true),
('276000', 'Prêts à l''étranger', true),
('277100', 'Prêts rétrocédés - versements aux administrations publiques nationales', true),
('277200', 'Prêts rétrocédés - versements aux entreprises publiques non financières nationales', true),
('277300', 'Prêts rétrocédés - versements aux institutions financières nationales', true),
('277400', 'Prêts rétrocédés - versements à d''autres secteurs de l''économie', true),
('277500', 'Prêts rétrocédés - versements à l''étranger', true),
('277600', 'Prêts sur dette avalisée intérieure', true),
('278100', 'Avances- Echéances Impayées', true),
('278200', 'Prêts à d''autres administrations publiques. Echéances Impayées', true),
('278300', 'Prêts aux entreprises publiques et semi publiques non financières. Impayées', true),
('278400', 'Prêts aux institutions. Echéances Impayées', true),
('278500', 'Autres Prêts Intérieurs. Echéances Impayées', true),
('278600', 'Prêts à l''étranger. Echéances Impayées', true),
('278700', 'Prêts retrocédés. Echéances Impayées', true),
('279000', 'Autres prêts et avances', true),
('281100', 'Amortissements des frais de recherche et de développement', true),
('281200', 'Amortissements des brevets, marques de fabrique, droits d''auteur', true),
('281300', 'Amortissements de la conception de systèmes d''organisation et des progiciels', true),
('281400', 'Amortissements des droits d''exploitation- Fonds de commerce', true),
('281800', 'Amortissements des immobilisations incorporelles pour le compte de tiers-acquisitions et travaux', true),
('281900', 'Amortissements des autres droits et valeurs incorporels', true),
('282100', 'Acquisitions et aménagements des sols et sous- sols', true),
('282300', 'Acquisitions, constructions et grosses réparations des immeubles', true),
('282400', 'Acquisitions et grosses réparations du matériel et mobilier', true),
('282500', 'Equipements militaires', true),
('282600', 'Prises de participation et cautionnements', true),
('282700', 'Prêts et avances', true),
('291200', 'Provisions pour dépréciation des brevets, marques de fabrique, droits d''auteur', true),
('291300', 'Provisions pour dépréciation de la conception de systèmes d''organisation et des progiciels', true),
('291400', 'Provisions pour dépréciation des droits d''exploitation- Fonds de commerce', true),
('291800', 'Provisions pour dépréciation des immobilisations incorporelles pour le compte de tiers-acquisitions et travaux', true),
('291900', 'Provisions pour dépréciation des autres droits et valeurs incorporels', true),
('292200', 'Provisions pour dépréciation des acquisitions et aménagements des sols et sous- sols', true),
('292300', 'Provisions pour dépréciation acquisitions, constructions et grosses réparations des immeubles', true),
('292400', 'Provisions pour dépréciation des acquisitions et grosses réparations du matériel et mobilier', true),
('292500', 'Provisions pour dépréciation des équipements militaires', true),
('292600', 'Provisions pour dépréciation des prises de participation et cautionnements', true),
('292700', 'Provisions pour dépréciation des prêts et avances', true),
('601100', 'Achats de petits matériels, fournitures de bureau et documentation', true),
('601200', 'Achats de carburants et lubrifiants', true),
('601300', 'Achats de carburants et lubrifiants pour les avions, navires et autres véhicules spéciaux', true),
('601400', 'Achats de fournitures et consommables pour le matériel informatique', true)
ON CONFLICT (code) DO UPDATE SET 
  libelle = EXCLUDED.libelle,
  est_active = true;