-- Insert NBE codes part 9/10 (53 codes from 651322 to 664100)
INSERT INTO public.nomenclature_nbe (code, libelle, est_active) VALUES
('651322', 'Remboursement de droits de sortie sur l''or', true),
('651329', 'Remboursement de droits de sortie sur autres minerais', true),
('651400', 'Reversements sur recettes', true),
('651600', 'Reversements sur commissions pour contrôle, analyse et certification', true),
('651900', 'Autres annulations, reversements et restitutions', true),
('652100', 'Indemnisations et transactions amiables', true),
('652200', 'Dépenses consécutives à des jugements et condamnations', true),
('652300', 'Indemnités d''éviction', true),
('654100', 'Valeurs comptables des immobilisations cédées', true),
('654200', 'Valeurs comptables des immobilisations mises au rébut', true),
('654300', 'Valeurs comptables des immobilisations admises en non valeur', true),
('659900', 'Autres charges exceptionnelles', true),
('659910', 'Créances irrécouvrables admises en non valeur', true),
('659920', 'Frais de recouvrement et de poursuites', true),
('659930', 'Subventions et dons', true),
('659940', 'Dépenses hors projets non ventilées', true),
('659950', 'Dépenses sur projets non ventilées', true),
('661100', 'Fonctionnaires de catégorie A', true),
('661200', 'Fonctionnaires de catégorie B', true),
('661300', 'Fonctionnaires de catégorie C', true),
('661400', 'Fonctionnaires de catégorie D', true),
('661500', 'Policiers', true),
('661600', 'Magistrats', true),
('661700', 'Traitement de base des militaires', true),
('661800', 'Rémunération des techniciens étrangers militaires', true),
('661900', 'Autres catégories de fonctionnaires et agents de l''Etat', true),
('662100', 'Rémunérations du personnel sous contrat et des décisionnaires', true),
('662110', 'Salaires et appointements du personnel sous contrat et des décisionnaires ivoiriens', true),
('662120', 'Salaires et appointements du personnel sous contrat et des décisionnaires étrangers', true),
('662200', 'Rémunérations du personnel occasionnel', true),
('662300', 'Rémunérations des gens de maison', true),
('662400', 'Rémunérations du personnel sous contrat en poste à l''étranger', true),
('662500', 'Rémunérations de techniciens et experts étrangers', true),
('662600', 'Pécule hommes de troupe', true),
('663100', 'Indemnités de fonction', true),
('663200', 'Indemnités de logement', true),
('663300', 'Indemnités de résidence', true),
('663400', 'Indemnités de responsabilité', true),
('663500', 'Indemnités de transport', true),
('663600', 'Indemnités de mutation', true),
('663700', 'Indemnités de départ à la retraite', true),
('663800', 'Indemnités d''utilisation des véhicules personnels des agents de l''Etat', true),
('663900', 'Autres primes et indemnités (dont indemnités de correction)', true),
('663910', 'Primes de recherche', true),
('663920', 'Primes académiques', true),
('663930', 'Primes d''encadrement', true),
('663940', 'Emoluments hospitaliers', true),
('663950', 'Emoluments hospitaliers particuliers', true),
('663960', 'Différentiel Santé', true),
('663970', 'Indemnités Para-médicales', true),
('663980', 'Indemnités forfaitaires Santé', true),
('663990', 'Autres primes et indemnités', true),
('664100', 'Cotisations retraite des personnels sous statut', true)
ON CONFLICT (code) DO UPDATE SET 
  libelle = EXCLUDED.libelle,
  est_active = true;