-- Insert NBE codes part 6/10 (53 codes from 614700 to 623600)
INSERT INTO public.nomenclature_nbe (code, libelle, est_active) VALUES
('614700', 'Entretien et réparation des véhicules, pneumatiques', true),
('614710', 'Entretien et réparation des véhicules', true),
('614720', 'Pièces de rechange des véhicules', true),
('614730', 'Pneumatiques', true),
('614800', 'Entretien et maintenance des avions, navires et autres véhicules spéciaux', true),
('614900', 'Autres dépenses d''entretien et de maintenance', true),
('614910', 'Frais de maintenance des équipements', true),
('614920', 'Petit outillage, pièces de rechange pour machines et engins', true),
('614930', 'Entretien et réparation des machines et engins', true),
('615100', 'Assurances des immeubles', true),
('615200', 'Assurances des véhicules automobiles, véhicules à 2 roues et tricycles', true),
('615300', 'Assurances des avions, navires et autres véhicules spéciaux', true),
('615400', 'Assurances des matériels et installations techniques', true),
('615900', 'Autres assurances', true),
('617300', 'Echantillons', true),
('617400', 'Foires et expositions', true),
('617500', 'Publications', true),
('617600', 'Cadeaux à la clientèle', true),
('617700', 'Frais de colloque, séminaires, conférences', true),
('617900', 'Autres frais de relations publiques', true),
('618100', 'Abonnements et consommations de téléphone, et d''autres télécommunications', true),
('618200', 'Abonnements et consommations de radiocommunication', true),
('618300', 'Abonnements et consommations Internet', true),
('618400', 'Affanchissement du courrier et autres frais de correspondance', true),
('618500', 'Valise diplomatique', true),
('618600', 'Franchises militaires', true),
('618700', 'Communiqués de presse, radio, télévision et frais de publicité', true),
('618900', 'Autres dépenses de communication', true),
('619900', 'Autres acquisitions de services', true),
('622100', 'Rémunérations de prestations extérieures', true),
('622110', 'Location de main-d''œuvre', true),
('622120', 'Travaux à façon', true),
('622200', 'Honoraires et frais annexes', true),
('622300', 'Frais d''actes et de contentieux, frais de justice', true),
('622400', 'Frais de formation au profit des tiers', true),
('622500', 'Services extérieurs de gardiennage', true),
('622600', 'Commissions pour contrôle, analyse et certification', true),
('622700', 'Frais d''audit et contrôle', true),
('622900', 'Autres prestations de services', true),
('622910', 'Rémunération des professeurs vacataires', true),
('622920', 'Rémunération des heures supplémentaires', true),
('622930', 'Rémunération des heures complémentaires', true),
('622940', 'Rémunération des moniteurs', true),
('622950', 'Abonnements, documentation', true),
('622960', 'Restauration', true),
('622970', 'Opérations programmées destinées à des tiers', true),
('622990', 'Autres prestations de services', true),
('623100', 'Prestation des organismes de formation résidents', true),
('623200', 'Prestation des organismes de formation non résidents', true),
('623300', 'Indemnités de formation à l''étranger', true),
('623400', 'Transport des agents en formation à l''étranger', true),
('623500', 'Indemnités de formation à l''intérieur', true),
('623600', 'Transport des agents en formation à l''intérieur', true)
ON CONFLICT (code) DO UPDATE SET 
  libelle = EXCLUDED.libelle,
  est_active = true;