-- Insert NBE codes part 8/10 (53 codes from 642520 to 651321)
INSERT INTO public.nomenclature_nbe (code, libelle, est_active) VALUES
('642520', 'Transferts pour dépenses en capital', true),
('642530', 'Transferts pour achat de biens et services', true),
('643100', 'Transferts aux Fonds Autonomes', true),
('643200', 'Transferts aux Institutions Nationales', true),
('643210', 'Transferts aux Institutions Nationales-dépenses de personnel', true),
('643220', 'Transferts aux Institutions Nationales-dépenses en capital', true),
('643230', 'Transferts aux Institutions Nationales-achats de biens et services', true),
('644100', 'Transferts aux ONG', true),
('644200', 'Transferts aux institutions éducatives et médico-sociales', true),
('644300', 'Transferts aux associations et autres organismes non lucratifs', true),
('644400', 'Transferts aux organismes non lucratifs en vue de manifestations ou congrès', true),
('644900', 'Autres Transfert en capital aux institutions a but non lucratif', true),
('645100', 'Bourses en Côte d''Ivoire', true),
('645200', 'Frais annexes aux bourses en Côte d''Ivoire', true),
('645300', 'Pécules et indemnités aux stagiaires et élèves hors fonctionnaires', true),
('645400', 'Bourses à l''étranger', true),
('645500', 'Frais annexes aux bourses à l''étranger', true),
('645600', 'Contribution aux frais de transport des élèves et étudiants', true),
('645700', 'Allocations chômage', true),
('645800', 'Aides et secours aux sinistrés et indigents', true),
('645810', 'Aides et secours aux sinistrés', true),
('645820', 'Aides et secours aux indigents', true),
('645900', 'Autres transferts aux ménages', true),
('646100', 'Transferts aux autorités supranationales', true),
('646200', 'Contributions aux organisations internationales', true),
('647100', 'Transferts aux Budgets annexes', true),
('647200', 'Transferts aux Comptes d''affectation spéciale', true),
('647300', 'Transferts aux Comptes de commerce', true),
('647400', 'Transferts aux Comptes de règlement avec les gouvernements ou autres organismes étrangers', true),
('647500', 'Transferts aux Comptes d''opérations monétaires', true),
('647600', 'Transferts aux Comptes de prêts', true),
('647700', 'Transferts aux Comptes d''avances', true),
('647800', 'Transferts aux Comptes de garanties et d''avals', true),
('648100', 'Pensions de retraite des fonctionnaires CGRAE', true),
('648120', 'Pensions de retraite des fonctionnaires CGRAE / Part Employeur', true),
('648200', 'Pensions de retraite des autres agents de l''Etat CNPS', true),
('648210', 'Pensions de retraite des autres agents de l''Etat CNPS / Part Employeur', true),
('648220', 'Pensions de retraite des autres agents de l''Etat CNPS / Part Salarié', true),
('649100', 'Rentes', true),
('649900', 'Autres transferts courants', true),
('651100', 'Remboursements de TVA', true),
('651200', 'Remboursements droits et taxes à l''importation', true),
('651300', 'Remboursements de droits et taxes à l''exportation', true),
('651310', 'Remboursements de droits uniques de sortie sur produits agricoles et dérivés', true),
('651311', 'Remboursement de droits uniques de sortie sur les bois', true),
('651312', 'Remboursement de droits uniques de sortie sur le café', true),
('651313', 'Remboursement de droits uniques de sortie sur le cacao', true),
('651314', 'Remboursement de droits uniques de sortie sur l''anacarde', true),
('651315', 'Remboursement de droits uniques de sortie sur la cola', true),
('651316', 'Remboursement de droits uniques de sortie sur le caoutchouc', true),
('651319', 'Remboursement de droits uniques de sortie sur autres produits agricoles et dérivés', true),
('651320', 'Remboursements de droits de sortie sur minerais', true),
('651321', 'Remboursement de droits de sortie sur le diamant', true)
ON CONFLICT (code) DO UPDATE SET 
  libelle = EXCLUDED.libelle,
  est_active = true;