-- Insert NBE codes part 3/10 (53 codes from 246900 to 271600)
INSERT INTO public.nomenclature_nbe (code, libelle, est_active) VALUES
('246900', 'Autres collections- œuvres d''art', true),
('247100', 'Stocks stratégiques ou d''urgence de carburants', true),
('247200', 'Stocks de céréales et autres produits alimentaires essentiels', true),
('247300', 'Stocks de régulation des marchés', true),
('247400', 'Stocks de produits pharmaceutiques', true),
('247900', 'Autres stocks', true),
('248100', 'Cheptel de trait', true),
('248200', 'Cheptel de reproduction', true),
('248900', 'Autres cheptels', true),
('251000', 'Bâtiments militaires', true),
('252100', 'Ouvrages et infrastructures militaires', true),
('253100', 'Mobilier', true),
('253200', 'Matériel et outillage (autre qu''informatique)', true),
('253300', 'Matériel informatique', true),
('253400', 'Voitures de fonction ou de service', true),
('253500', 'Véhicules de transports en commun militaires', true),
('253600', 'Véhicules de transports utilitaires militaires', true),
('253700', 'Matériels de transport fluvial et maritime militaires', true),
('253710', 'Matériels de transport fluvial militaires', true),
('253720', 'Matériels de transport maritime militaires', true),
('253800', 'Matériels de transport aérien militaires', true),
('253900', 'Autres équipements militaires', true),
('261100', 'Prises de participations dans des entreprises publiques nationales', true),
('261110', 'Participations majoritaires', true),
('261120', 'Participations minoritaires avec minorité de blocage', true),
('261130', 'Participations minoritaires sans minorité de blocage', true),
('261140', 'Titres de placement', true),
('261210', 'Participations majoritaires', true),
('261220', 'Participations minoritaires avec minorité de blocage', true),
('261230', 'Participations minoritaires sans minorité de blocage', true),
('261310', 'Participations majoritaires', true),
('261320', 'Participations minoritaires avec minorité de blocage', true),
('261330', 'Participations minoritaires sans minorité de blocage', true),
('261340', 'Titres de placement', true),
('261910', 'Prises de participations,  p/cpte d''entreprises publiques nles', true),
('261920', 'Prises de participations,  p/cpte d''institutions financières nles', true),
('261930', 'Prises de participations,  p/cpte d''autres secteurs de l''économie', true),
('261940', 'Prises de participations,  pour le compte de tiers extérieurs', true),
('261990', 'Autres prises de participations,  pour le compte de tiers', true),
('264100', 'Dépôts et cautionnements-loyer d''avance', true),
('264200', 'Dépôts et cautionnements-gaz', true),
('264300', 'Dépôts et cautionnements-électricité', true),
('264400', 'Dépôts et cautionnements-gaz', true),
('264500', 'Dépôts et cautionnements-téléphone', true),
('264600', 'Dépôts et cautionnements-télex', true),
('264700', 'Dépôts et cautionnements-Ensemble de gestion', true),
('264900', 'Autres dépôts et cautionnement', true),
('271100', 'Avances aux Sociétés d''Etat', true),
('271200', 'Avances aux Sociétés d''Economie Mixte', true),
('271300', 'Avances aux institutions financières', true),
('271400', 'Avances aux entreprises privées non financières', true),
('271500', 'Avances au personnel pour achats de logements', true),
('271600', 'Avances au personnel pour achats de véhicules', true)
ON CONFLICT (code) DO UPDATE SET 
  libelle = EXCLUDED.libelle,
  est_active = true;